### ISSUE TITLE
Update to version 0.9.8

### ISSUE THREAD

**Issue by blanchardjeremy** [theatlantic/django-chosen#17]
Chosen is at 0.9.8 now:

https://github.com/harvesthq/chosen/tree/v0.9.8

It would be great to have django-chosen updated to match that version.

Thanks!

**Comment by fdintino** [comment]
I'm closing this in favor of pull request #27, which updates to chosen 0.10.0, since that is a more recent than this one. Apologies for the unforgivable delay in responding to this pull request. We have switched away from django-chosen to [django-select2-forms](https://github.com/theatlantic/django-select2-forms) which has all of the features of django-chosen plus ajax autocomplete and better admin support.
