### ISSUE TITLE
ChosenModelMultipleChoiceField, blocking null=True ?

### ISSUE THREAD

**Issue by domguard** [theatlantic/django-chosen#7]
I have a model in an app like this :

```
class Member(models.Model):
    ....
    category = models.ManyToManyField(MemberCategory, 
                      blank=True, 
                      null=True, verbose_name=_(u'category'))
```

admin.py:   

```
class MemberAdminForm(forms.ModelForm):
    category = chosenforms.ChosenModelMultipleChoiceField(
        overlay=_(u"Choose one or more categories"), 
        queryset=MemberCategory.objects.all())    
```

With this setup, I cannot save the model without choosing a category : it's like if null=True was overriden

**Comment by fdintino** [comment]
Thanks for the report, I'll take a look.

**Comment by fdintino** [comment]
I would try adding `required=False` to your form field. So your form should look like this:

``` python
class MemberAdminForm(forms.ModelForm):
    category = chosenforms.ChosenModelMultipleChoiceField(
        required=False,
        overlay=_(u"Choose one or more categories"), 
        queryset=MemberCategory.objects.all())
```

(I can't say for certain, not having tested it, but I think the queryset argument might be unnecessary)

When you don't override the individual fields in a model form, the form class auto-detects the null and blank attributes of the fields in the model and sets the required property accordingly. However, if you specify the form field explicitly it takes the default keyword arguments for `django.forms.fields.Field`, where `required=True`, so to be safe you should add in `required=False` to ensure otherwise.

Let me know if you still have the problem with those changes.

**Comment by domguard** [comment]
You're right about `required` , works now, thanks for the lesson ;)

**Comment by fdintino** [comment]
Glad I could help!
